@host = http://localhost
@port = 5090

@PackageTracking.API_HostAddress = http://localhost:5090


GET {{PackageTracking.API_HostAddress}}/api/receiver

###

GET {{PackageTracking.API_HostAddress}}/api/receiver/2

###

POST {{PackageTracking.API_HostAddress}}/api/receiver
Content-Type: application/json

{
    "Description": "Receiver 5",
    "ContactEmail": "receiver5@test.com",
    "ContactNumber": "12-123456789",
    "DocumentNumber": "123456789"
}

###

DELETE {{PackageTracking.API_HostAddress}}/api/receiver/1

###

PATCH {{PackageTracking.API_HostAddress}}/api/receiver/8
Content-Type: application/json

{
    "Description": "Receiver 8",
    "ContactEmail": "receiver8@test.com",
    "ContactNumber": "11-123456789",
    "DocumentNumber": "231231233"
}

###
