@host = https://localhost
@port = 7212
@token = CfDJ8AEIbZhBaClLipeCLuNS1GlYrEtBGnV4bg3fqQe--FuVkzMPwN8oKUznPX9184DJYFJDYnwWvOmP37XPgNJVRRPckd-feYKzhcMpqP8nPktWaB2_-cfSe8omGoNSakq9DNgz-eAbHHTGAYvD9GUqdPzLEKU4K8rD4c6PzTTcLrgrzdP17uvVwg9v0E0HlLbtMAaW4tkrn541dAjGETqpSCZ5Sg5oUE8k-Wbnl3PBVU6FHwPeiDBp5J7Vgu1hl3upL0KZg2oLFj6pI1SXXosOtZw5aH7jtrJNI5rIn-zHQd88h3nwGLmP6A37dV6maDzbgEu1BPPNNuXqp4raAgXFlpLWUn0wKZ0LHJY8xoOnWS1puimzboAG9LMc8x5XE2mcdfIeT52qf3u6MyuoQm1PzioeXJOckqz0rXleEB2g44Kxkhflqh4ouhzE5o_jt_El97SCuj7q_kWv8G_GjANApj2tLjYz0uipC4GPK2wjItNfYqmikRk3xDhGZvxUQcrinEVGNJvOj5X4gnqRa27NPJUp3ZosjCgLEVT4Jp-aNp7uUAGHcMe3BtBKVHUDEo-j0bdmaINVHRsGG77TypcQIQYlSqdm1vA41-RHs_VYpSwcxU2m7nNAifp_dtpec6LX9hdg9nIHVnXpy-H80RL42xEv9f4-pLtX-6b8mEkAlIsbjWC37Q67zZxZqp7iCndAmGf9Kc4OcFCyRybk5bV_9tOKNTBTLx9CDEigZ1AM3u2mAv2P36Tszy8rUPElL9noK9-udrhqbYNqsBqGv_suA5A5IhEtig4yRFRhZxzwue5JhNMyRGXBSmZRyXDCwWG-FUJPzJNuaA7CQoHMkn-XFOXlLMHkL9bMo5ZFhmHi-G6EF8ewBiexOYY5E9vh0Pti3w


@PackageTracking.API_HostAddress = {{host}}:{{port}}

GET {{PackageTracking.API_HostAddress}}/api/receiver
Authorization: Bearer {{token}}
###

GET {{PackageTracking.API_HostAddress}}/api/receiver/2
Authorization: Bearer {{token}}

###

POST {{PackageTracking.API_HostAddress}}/api/receiver
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Description": "Receiver 5",
    "ContactEmail": "receiver5@test.com",
    "ContactNumber": "12-123456789",
    "DocumentNumber": "123456789"
}

###

DELETE {{PackageTracking.API_HostAddress}}/api/receiver/1
Authorization: Bearer {{token}}

###

PATCH {{PackageTracking.API_HostAddress}}/api/receiver/8
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Description": "Receiver 8",
    "ContactEmail": "receiver8@test.com",
    "ContactNumber": "11-123456789",
    "DocumentNumber": "231231233"
}

###

POST {{PackageTracking.API_HostAddress}}/api/receiver/{receiverId}/package
Content-Type: application/json
Authorization: Bearer {{token}}

{
  //CreatePackageCommand
}

###

POST {{PackageTracking.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password#123"
}

###

POST {{PackageTracking.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password#123"
}

###

PATCH {{PackageTracking.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "dateofBirth": "2010-01-01",
    "nationality": "Mexican"
}

###

POST {{PackageTracking.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "userEmail": "felipe@test.com",
    "roleName": "User"
}

###

DELETE {{PackageTracking.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "userEmail": "owner@test.com",
    "roleName": "User"
}

###